DROP TABLE IF EXISTS users;

CREATE TABLE users(
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR (250) NOT NULL,
   lastname VARCHAR (250) NOT NULL,
   email VARCHAR (250) NOT NULL UNIQUE,
   username VARCHAR (250) NOT NULL UNIQUE,
   password VARCHAR (250) NOT NULL UNIQUE
);